name: Docker Image CI

on:
  push:
    branches:
    - feature* 
    - bugfix*
  pull_request:
    branches: 
    - master
    - development
    
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd bulletin-board-app && docker build . --file Dockerfile --tag node-bulletin-board:$(date +%s)
